repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-ast
      - id: trailing-whitespace
      - id: check-docstring-first
      - id: check-toml
      - id: check-yaml
        exclude: packaging/.*
      - id: end-of-file-fixer
      - id: check-added-large-files
        args: ['--maxkb=50000']
      - id: check-merge-conflict
        args: ['--assume-in-merge']

  - repo: https://github.com/PyCQA/autoflake
    rev: v1.5.3
    hooks:
      - id: autoflake
        args: ['--remove-all-unused-imports', '--remove-duplicate-keys']

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args: [--config=setup.cfg]

  - repo: https://github.com/omnilib/ufmt
    rev: v2.0.0b1
    hooks:
      - id: ufmt
        additional_dependencies:
          - black == 22.3.0
          - usort == 1.0.2

  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.14
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-gfm
          - mdformat-black
          - mdformat_frontmatter
